name: 'Veracode Pipeline Scan Resutls'
description: 'Process Veracode Pipeline Scan Results and close a check run on GitHub'
author: 'Vincent Deng'
inputs:
  token:
    description: 'your GITHUB_TOKEN'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'