name: 'Veracode GitHub Workflow Tool Helper functions'
description: 'Helper functions for GitHub Workflow Tool - Currently supports validations and process scan results.'
author: 'Vincent Deng'
inputs:
  action:
    description: 'Action to take'
    required: true
  vid:
    description: 'Veracode ID'
    required: true
  vkey:
    description: 'Veracode Key'
    required: true
  appname:
    description: 'Veracode Application Name'
    required: true
  token:
    description: 'your GITHUB_TOKEN'
    required: false
  check_run_id:
    description: 'GitHub Check Run ID'
    required: false
  source_repository:
    description: 'Source Repository'
    required: false
  fail_checks_on_policy:
    description: 'Fail Checks if Policy Fails'
    required: false
  fail_checks_on_error:
    description: 'Fail Checks if there are Build Errors'
    required: false
  sandboxname:
    description: 'Sandbox Name'
    required: false
  policyname:
    description: 'Policy Name'
    required: false
  path:
    description: 'Path'
    required: false
  start_line:
    description: 'Start line'
    required: false
  end_line:
    description: 'End line'
    required: false
  break_build_policy_findings:
    description: 'Break build on policy findings'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'